POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST http://localhost:8082/book/list
Content-Type: application/x-www-form-urlencoded


###

POST http://localhost:8082/book/search
Content-Type: application/x-www-form-urlencoded

course=K

###

POST http://localhost:8082/book/select_x
Coutent-Type: application/x-www-form-urlencoded

isbn=9787-212-222-331

###

POST http://localhost:8082/teacher/list
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8082/course/list
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8082/course/list/by/major

###
POST http://localhost:8082/major/by/year
Content-Type: application/x-www-form-urlencoded

year=2019

###
POST http://localhost:8082/course_open/list
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8082/course_open/insert
Content-Type: application/x-www-form-urlencoded

book=5&teacher=868&year=2018&semester=3&course=G122112

###
