@startuml
title 登录流程图
start
if (loginTeacher?) then (yes)
    #green:Success;
    stop
endif
if (loginStudent?) then (yes)
    #green:Success;
    stop
endif
if (loginAdmin?) then (yes)
    #green:Success;
    stop
endif
#pink:Fail;
stop
@enduml

@startuml
title 登录流程图
start
if (是教师账号且密码正确) then (yes)
    #lightGreen:教师登录成功;
    stop
endif
if (是学生账号且密码正确) then (yes)
    #lightGreen:学生登录成功;
    stop
endif
if (是管理员账号且密码正确) then (yes)
    #lightGreen:管理员登录成功;
    stop
endif
#pink:登录失败;
stop
@enduml


@startuml
title 登录化简后流程图
(*) --> "1"
if "2" then
-->[yes] "5"
--> "7"
else
-->[no] if "3" then
        -->[yes] "5"
        else
        -->[no] if "4" then
                -->[yes] "5"
                else
                --> [no] "6"
                --> "7"
                --> (*)
                endif
        endif
endif
@enduml